### ISSUE TITLE
Issues deploying to Now

### ISSUE THREAD

**Issue by smockle** [greenkeeper-keeper/reference-instance#108] opened 2017-09-22 04:13 UTC
# ATTEMPT 1: One-Click Deploy

I get an error when I try to deploy with Now: “Deploy failed, please check the repo and try again.”

1. Click the [“Deploy with Now” link](https://deploy.now.sh/?repo=https://github.com/greenkeeperkeeper/reference-instance&env=GITHUB_TOKEN&env=GITHUB_WEBHOOK_SECRET) in the `greenkeeper-keeper/reference-instance` README

2. Paste a `ZEIT API TOKEN` (from https://zeit.co/account/tokens)

3. Paste a `GITHUB_TOKEN` (from https://github.com/settings/tokens, with `read:repo_hook` & `repo` scopes, as recommended on https://github.com/greenkeeper-keeper/meta#things-you-will-need)

4. Paste a `GITHUB_WEBHOOK_SECRET` (created with `ruby -rsecurerandom -e 'puts SecureRandom.hex(20)'` as recommended on https://developer.github.com/webhooks/securing/)

5. Click “Deploy”

6. The error message “Deploy failed, please check the repo and try again.” appears at the top of the page.

I get the same error message if I check the “Deploy using Docker” checkbox before clicking “Deploy”.

# ATTEMPT 2: Local Deploy

I also get an error when I try to deploy from my machine using Now (i.e. _without_ using the one-click deploy link in `greenkeeper-keeper/reference-instance`’s README):

1. Clone the `greenkeeper-keeper/reference-instance` locally and change working directory to the newly-cloned location.

2. Install dependencies and run build: `npm i && npm run build`

3. Following the instructions in the Now docs, add [secrets](https://zeit.co/blog/environment-variables-secrets) (used by `greenkeeper-keeper/reference-instance` as environment variables):

```Bash
now secret add gk-zeit-token <snip>
now secret add gk-github-token <snip>
now secret add gk-github-webhook-secret <snip>
```

4. Deploy using Now, with environment variables from Now secrets, via npm (rather than Docker) and publicly: `now -e PORT=8080 -e GITHUB_TOKEN=@gk-github-token -e GITHUB_WEBHOOK_SECRET=@gk-github-webhook-secret --npm --public`

5. Create a new webhook for the repo I want to watch with greenkeeper-keeper: https://github.com/smockle/REPO/settings/hooks

6. Paste a `Payload URL`, in the form “https://reference-instance-FOO.now.sh/payload”

7. Ensure `Content Type` is `application/x-www-form-urlencoded`

8. Paste a `Secret` (the same used in Step 3 above)

9. Under `Which events would you like to trigger this webhook?`, select “Let me select individual events”. Uncheck “Push” and check “Status” (as recommended on https://github.com/greenkeeper-keeper/meta#setting-up-webhooks)

10. Ensure `Active` is checked.

11. Click “Add Webhook”

12. A “Recent Deliveries” section will appear at the bottom of the page. Clicking the link will expand the delivery. It appears that GitHub attempted to test the new webhook by POSTing some data to the server. The response returned by the server is `{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}`

**Comment by travi** [comment] 2017-09-22 04:27
Sorry that this has given you so much trouble, but thanks for the detailed report. Does Now provide any server logs when failures like this occur? 

My initial guess is that the server is failing to start, which tends to be because of a missing env var definition. It looks like you've defined what you should need, but seeing the logs should help us confirm that.

**Comment by smockle** [comment] 2017-09-22 04:39
> Does Now provide any server logs when failures like this occur?

It does (`now logs <deploymentURL>`)! I didn’t think to check before because I’m very new to Now. 🙈 

Here are the relevant lines:

```
09/21 09:34 PM  
    170922/043410.528, [log,startup] data: Server started at http://0.0.0.0:8080
09/21 09:34 PM  170922/043441.970, [error] message: Uncaught error: Cannot read property 'config' of undefined, stack: TypeError: Uncaught error: Cannot read property 'config' of undefined
    at validatePayloadAndProcess (/home/nowuser/src/node_modules/hapi-greenkeeper-keeper/lib/plugin.cjs.js:484:40)
    at handler (/home/nowuser/src/node_modules/hapi-greenkeeper-keeper/lib/plugin.cjs.js:541:7)
    at Object.internals.handler (/home/nowuser/src/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/home/nowuser/src/node_modules/hapi/lib/handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (/home/nowuser/src/node_modules/hapi/lib/protect.js:60:12)
    at exports.execute (/home/nowuser/src/node_modules/hapi/lib/handler.js:26:22)
    at each (/home/nowuser/src/node_modules/hapi/lib/request.js:416:16)
    at iterate (/home/nowuser/src/node_modules/items/lib/index.js:36:13)
    at done (/home/nowuser/src/node_modules/items/lib/index.js:28:25)
    at internals.Auth.payload (/home/nowuser/src/node_modules/hapi/lib/auth.js:248:16)
09/21 09:34 PM  Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'config' of undefined
    at validatePayloadAndProcess (/home/nowuser/src/node_modules/hapi-greenkeeper-keeper/lib/plugin.cjs.js:484:40)
    at handler (/home/nowuser/src/node_modules/hapi-greenkeeper-keeper/lib/plugin.cjs.js:541:7)
    at Object.internals.handler (/home/nowuser/src/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/home/nowuser/src/node_modules/hapi/lib/handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (/home/nowuser/src/node_modules/hapi/lib/protect.js:60:12)
    at exports.execute (/home/nowuser/src/node_modules/hapi/lib/handler.js:26:22)
    at each (/home/nowuser/src/node_modules/hapi/lib/request.js:416:16)
    at iterate (/home/nowuser/src/node_modules/items/lib/index.js:36:13)
    at done (/home/nowuser/src/node_modules/items/lib/index.js:28:25)
    at internals.Auth.payload (/home/nowuser/src/node_modules/hapi/lib/auth.js:248:16)
09/21 09:34 PM  170922/043441.970, [response] http://<snip>:8080: post /payload {} 500 (42ms)
```

**Comment by smockle** [comment] 2017-09-22 04:44
If I understand correctly, on [this line](https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper/blob/master/src/handler.js#L20) in `greenkeeper-keeper/hapi-greenkeeper-keeper`, `config` is not found on `request.payload.hook`?

**Comment by travi** [comment] 2017-09-22 04:46
yeah, thats what i'm thinking as well. (it looks like i need to enable source-maps for the plugin to make that a little simpler to track down).

if thats the issue, it suggests that the payload you are getting in the webhook from github doesnt have the expected shape. could you show me the payload content from the "recent deliveries" that you saw earlier for that `ping` event?

**Comment by smockle** [comment] 2017-09-22 04:51
We figured it out!

Step 7 above is the issue:
> Ensure `Content Type` is `application/x-www-form-urlencoded`

The webhook’s `Content Type` should be `application/json`, _not_ `application/x-www-form-urlencoded`. I deleted the webhook I’d created, then made a new one with the proper `Content Type`, and now I get a successful response! 🎊 

Thanks very much for the help debugging this @travi. I greatly appreciate it.

**Comment by smockle** [comment] 2017-09-22 04:57
For reference, here is a snippet of the `application/json` payload:

```JSON
{
  "zen": "It's not fully shipped until it's fast.",
  "hook": {
    "type": "Repository",
    "name": "web",
    "active": true,
    "events": [
      "status"
    ],
    "config": {
      "content_type": "json"
    }
}
```

And here is a snippet of the `application/x-www-form-urlencoded` payload:

``` JSON
{
  "zen": "It's not fully shipped until it's fast.",
  "hook": {
    "type": "Repository",
    "name": "web",
    "active": true,
    "events": [
      "status"
    ],
    "config": {
      "content_type": "form"
    }
}
```

The payload shape in both cases includes `request.payload.hook.config`, so I don’t quite understand why we saw a `Cannot read property 'config' of undefined` message in the logs. 🤔

**Comment by travi** [comment] 2017-09-22 05:01
sure thing! glad we got it working :tada: 

did you find step 7 documented somewhere? i'd like to update it if i have it wrong, but i'm not seeing it now. clearly, i could improve that info either way, so this is more clear for others.

my team uses this fairly heavily and it satisfies our needs pretty well, but its still a work in progress, so don't hesitate to provide feedback if your needs stretch beyond the current behavior.

**Comment by travi** [comment] 2017-09-22 05:03
yeah, that is odd that we were seeing the error that we were. clearly the code expects the shape you included here and is intended to provide a helpful error in the response so that this is simpler to fix. 

i'm now curious if the content-type of the response is set to `application/x-www-form-urlencoded`, even though the payload is `json`. that could certainly confuse hapi and result in it failing to parse the payload properly.

**Comment by smockle** [comment] 2017-09-22 05:14
> did you find step 7 documented somewhere? i'd like to update it if i have it wrong, but i'm not seeing it now.

Nope, none of the `greenkeeper-keeper` documentation I saw had `Content Type` instructions. It was totally my own fault. 😊

GitHub’s default `Content Type` for web hooks is `application/x-www-form-urlencoded`. If you consider adding a comment about `application/json`, I’d recommend the [“Setting up webhooks”](https://github.com/greenkeeper-keeper/meta#setting-up-webhooks) section.

> my team uses this fairly heavily and it satisfies our needs pretty well, but its still a work in progress, so don't hesitate to provide feedback if your needs stretch beyond the current behavior.

It’s really great! Thanks for all your work on this project! Following up on Twitter about this was above-and-beyond. Unexpected and appreciated. 😊

**Comment by travi** [comment] 2017-09-22 05:24
yeah, that default has tripped me up a number of times. unfortunately that the suggestion fails to respond as intended, but now that i know about it, i should be able to resolve that. either way, this is a good nudge to clean up the setup instructions.

certainly no worries on the help. i'm glad the @greenkeeperio team connected us and that you find the project useful :)

**Comment by travi** [comment] 2017-09-22 05:42
less important now that we got things solved, but i did configure sourcemaps in the hapi plugin, so there should be a new version of this instance available shortly if youre interested in updating your instance in case there is a need to dive into the logs again.

i actually keep my instance up to date by having it maintain itself. commits to master of my instance deploy automatically and greenkeeper PRs that get merged result in commits to master, so it ends up being fully automated.

**Comment by travi** [comment] 2018-01-28 04:23
i finally got a note about the "Content type" added to the [setup details](https://github.com/greenkeeper-keeper/meta#setting-up-webhooks), so i think the outstanding details from issue, other than those captured in greenkeeper-keeper/hapi-greenkeeper-keeper#312, are handled. if that is not true. please open a new issue.

**Closed as completed by travi** 2018-01-28 04:23 UTC
